# Generated by Django 4.2.3 on 2023-07-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
